### ISSUE TITLE
Cannot create a project

### ISSUE THREAD

**Issue by splitlucidity** [tixl3d/tixl#738]
When I open TiXL and click the + next to Project Hub to create a new project, it fails whenever I hit create, and provides me with this message to copy

Failed to create project "MyProject" in "".

This should never happen - please file a bug report.
Currently this error is unhandled, so you will want to manually delete the project from disk.

 - OS: Windows 11
 - Version: TiXL 4.0.5
 - Graphics card and resolution: RTX 2060 SUPER // 2560x1440

1. Go to TiXL 4.0.5 installation path
2. Open TiXL 4.0.5.exe
3. Create Project beside Project Hub
4. Click Create
5. See error code

Expected behavior:
I expected to open the program and be able to create a project to start working with. 

**Screenshots**

<img width="2558" height="1393" alt="Image" src="https://github.com/user-attachments/assets/32f23d45-3553-47e0-a70c-87f11bc33a3d" />

Entire Command Prompt Code:

Starting T3 Editor
Creating EditorUi
Creating DX11ShaderCompiler
Enabling DPI aware scaling
Creating SplashScreen
Initializing logging
Info: Starting 4.0.5
Debug: Initializing ProgramWindows...
Debug: Detected display adapters...
Debug:   #0: NVIDIA GeForce RTX 2060 SUPER / 7.8GB  -> rated 4.0
Debug:   #1: NVIDIA GeForce RTX 2060 SUPER / 7.8GB  -> rated 4.0
Debug:   #2: Microsoft Basic Render Driver / 0.0GB  -> rated 0.1
Debug: Creating Device...
Debug: Initializing UiContentContentDrawer...
Debug: Initialize Camera Interaction...
Debug: Initialize Resource Manager...
Debug: fullscreen-texture.hlsl - vsMain compiled in: 18.3 ms
Debug: fullscreen-texture.hlsl - psMain compiled in: 2.3 ms
Debug: Initialize User Interface...
Debug: Loading projects...
Warning: Already registered provider T3.Core.Stats.OpUpdateCounter
Debug: C:\Users\14163\Documents\TiXL\MyProject\bin\Debug\net9.0\OperatorPackage.json doesn't exist yet
Warning: Could not load package info from path C:\Users\14163\Documents\TiXL\MyProject\bin\Debug\net9.0\OperatorPackage.json
Warning: MyProject MyProject needs to be compiled because the version info file does not exist.
Error: Restore failed:
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

Error: Failed to recompile project 'MyProject'
Info: Examples: Loading symbols...
Info: t3.unsplash: Loading symbols...
Info: t3.ndi: Loading symbols...
Info: Types: Loading symbols...
Info: user.pixtur: Loading symbols...
Info: t3.spout: Loading symbols...
Info: Lib: Loading symbols...
Warning: Error loading symbol child a60138eb-2a78-40a9-899a-e7593723a945
Error: Problem obtaining children of DemoProjectTests (cf9a082f-490c-4b59-8a9a-eee161420d06)
Debug: render-volume-slice-cs.hlsl - main compiled in: 1.6 ms
Warning: Found input entry in ui file for symbol 'VertexShaderFromSource', but no corresponding input in symbol. Assuming that the input was removed and ignoring the ui information.
Warning: Found input entry in ui file for symbol 'VertexShaderFromSource', but no corresponding input in symbol. Assuming that the input was removed and ignoring the ui information.
Warning: Found output entry in ui file for symbol 'VertexShaderFromSource', but no corresponding output in symbol. Assuming that the output was removed and ignoring the ui information.
Warning: Skipping UI child definition in DemoProjectTests cf9a082f-490c-4b59-8a9a-eee161420d06 for undefined child e23bd572-dad8-42e2-bb18-3bfae9319aed
Debug: render-volume-slice-cs.hlsl - main loaded from cache
Debug: Found no input ui entry for symbol child input 'VertexShaderFromSource.ShaderSource' - creating a new one
Debug: Found no input ui entry for symbol child input 'VertexShaderFromSource.EntryPoint' - creating a new one
Debug: Found no input ui entry for symbol child input 'VertexShaderFromSource.DebugName' - creating a new one
Info: Updated 7 symbol packages in 2972ms
Debug: Capturing Midi devices...
Debug: Found 86 examples for 86 operators out of 114 potential examples
Info: Startup took 4269ms.
Debug: C:\Users\14163\AppData\Roaming\TiXL\resolutions.json doesn't exist yet
Error: Restore failed:
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

Error: Failed to compile new project
Error: Failed to create project "MyProject" in "".

This should never happen - please file a bug report.
Currently this error is unhandled, so you will want to manually delete the project from disk.
Error: Restore failed:
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

Error: Failed to compile new project
Error: Failed to create project "MyProject" in "".

This should never happen - please file a bug report.
Currently this error is unhandled, so you will want to manually delete the project from disk.

**Comment by sense-amr** [comment]
Most likely you already have a project Called "My Project" i would suggest making a NEW project name and try and see if you still get the error .. I've only encountered THIS particular error when an existing project name is there..

**Comment by pixtur** [comment]
I believe that might be fix in the upcoming version.
I will let you know, once the release preview is ready.

**Comment by splitlucidity** [comment]
> Most likely you already have a project Called "My Project" i would suggest making a NEW project name and try and see if you still get the error .. I've only encountered THIS particular error when an existing project name is there..

I just tried creating a bunch of projects with random names and they didn't work...

**Comment by bennoH2025** [comment]
@splitlucidity Is it possible that you currently have TiXL installed in the C Programs directory? Try installing TiXL somewhere in your user-Documents-directory and then starting from there TiXL, but delete the existing installation first. 
Maybe that will solve your problem. I'm not very//not so deep familiar with TiXL, but I've had similar problems that were solved this way.

Greetings from mountainous Switzerland

**Comment by sense-amr** [comment]
Have you set a namespace ? initially on start up of TixL?

**Comment by splitlucidity** [comment]
> [@splitlucidity](https://github.com/splitlucidity) Is it possible that you currently have TiXL installed in the C Programs directory? Try installing TiXL somewhere in your user-Documents-directory and then starting from there TiXL, but delete the existing installation first. Maybe that will solve your problem. I'm not very//not so deep familiar with TiXL, but I've had similar problems that were solved this way.
> 
> Greetings from mountainous Switzerland

Howdy from Canada! 

I only installed any TiXL/TOOLL3 .exes on my E Drive, maybe because I have other versions of this program on the same drive, it's bugging out? I will try to install it on my C Drive this time and see if that makes a difference.

**Comment by splitlucidity** [comment]
Reinstalled using the same steps I took before, but this time on my C Drive, and I'm still getting the same issues. I wonder if you can't have a parallel install of TOOLL3 and TiXL even if they're on different drives. I'm hesitant to uninstall since I haven't been able to get TiXL running and with every other program I've used, I've been able to parallel install them.

**Comment by sense-amr** [comment]
The user settings are by default found in your \users\yourname\AppData\Roaming\TiXL
there are also other files which are related to the project and these are found in \Documents\TiXL unless of course you specfied your own location for them .. My recommendation would be to go to this folder and rename it TiXL Projects_old or something similar .. this will force TixL to make a NEW projects folder.. 
which should then allow you to make a new Project

**Comment by sense-amr** [comment]
https://github.com/user-attachments/assets/b6123703-ae75-4b9d-874a-f3eded008888

**Comment by sense-amr** [comment]
Error: Failed to create project "MyProject" in "". <-- btw this pretty much says it all .. its saying you DO NOT have a namespace set..

**Comment by sense-amr** [comment]
> Reinstalled using the same steps I took before, but this time on my C Drive, and I'm still getting the same issues. I wonder if you can't have a parallel install of TOOLL3 and TiXL even if they're on different drives. I'm hesitant to uninstall since I haven't been able to get TiXL running and with every other program I've used, I've been able to parallel install them.

Tixl and Tooll3 use completely different architecture .. so there is ZERO conflict or connection between the two

**Comment by splitlucidity** [comment]
> The user settings are by default found in your \users\yourname\AppData\Roaming\TiXL there are also other files which are related to the project and these are found in \Documents\TiXL unless of course you specfied your own location for them .. My recommendation would be to go to this folder and rename it TiXL Projects_old or something similar .. this will force TixL to make a NEW projects folder.. which should then allow you to make a new Project

It won't let me upload a video I screen recorded for this, so I uploaded it to my Google Drive: https://drive.google.com/file/d/1qufFSCC9G3SIg_96jAexj_oH9yXUz9Gs/view?usp=sharing

I did what you said about changing the folder name for the projects, and even though it created a new projects folder, it still gave me the same error. I also somehow forgot to include in my reply that I had tried using a namespace within the project creation section, and it didn't change a thing for whatever reason. I'm sorry if this has been inconvenient and/or a nuisance. I genuinely have no idea why this isn't working.

**Comment by sense-amr** [comment]
So when you first installed TiXL it asks you to set  a namespace .. this is the place to set your namespace.. once this is set .. then ALL of your projects will be linked to that namespace for example sense.balls .. 
If you DID NOT set a namespace then it has nowhere to put your project and i would easily imagine this would result in a failure to create a new project .. 

BTW you CANNOT change any folder names WHILE TiXL is open :)

**Comment by sense-amr** [comment]
> > The user settings are by default found in your \users\yourname\AppData\Roaming\TiXL there are also other files which are related to the project and these are found in \Documents\TiXL unless of course you specfied your own location for them .. My recommendation would be to go to this folder and rename it TiXL Projects_old or something similar .. this will force TixL to make a NEW projects folder.. which should then allow you to make a new Project
> 
> It won't let me upload a video I screen recorded for this, so I uploaded it to my Google Drive: https://drive.google.com/file/d/1qufFSCC9G3SIg_96jAexj_oH9yXUz9Gs/view?usp=sharing
> 
> I did what you said about changing the folder name for the projects, and even though it created a new projects folder, it still gave me the same error. I also somehow forgot to include in my reply that I had tried using a namespace within the project creation section, and it didn't change a thing for whatever reason. I'm sorry if this has been inconvenient and/or a nuisance. I genuinely have no idea why this isn't working.

The issue HERE is that you tried creating the namespace LATER.. you need to do this at the point where TiXL is first installed and you set it there.. you CANNOT on the fly change namespace as it stands .. and this is not really a good practice .. you need to create it at the very first time you start TiXL after installing it

and this is according to what i saw in your video ..

**Comment by splitlucidity** [comment]
Okay, since you said I had to create the namespace when TiXL is first installed, as it asks you to do so, I decided to record the entire installation process all over again because I genuinely feel like I've missed something, and I feel like providing as much information as possible will be the most helpful. 

https://drive.google.com/file/d/1BWoZT6tT9dfzeGaQHT0OxGJsj9mJGH1b/view?usp=sharing

As you can see, upon arrival in TiXL immediately after installation, I was not prompted to create a namespace; I had to click on the Project Hub. Unless there is somewhere else to create a namespace and I somehow missed it/overlooked it, I did not come across anywhere in the process for it asking me to create a namespace. I know that the usersettings.json file retains even after uninstalls so I changed the folder location to be \Documents\TiXL, thinking that that's what it should be set to, as per your earlier comments, but as you can see, it said that the folder does not exist, which is odd to me because if that is the default location for the folder, why doesn't it exist? I know I specified it, but the pathway would be the same regardless of whether I specified it. If it is to be created after the creation of a project for the first time then sure, but this didn't work. I'm seriously confused and I promise I'm not trying to be difficult, I just seriously don't get why this isn't working, despite following everything now.

**Comment by splitlucidity** [comment]
"I know that the usersettings.json file retains even after uninstalls so I changed the folder location to be \Documents\TiXL"

ProjectsFolder pathway in the .json file is what I should have said, I realize the wording of "changed the folder location" sends the wrong idea.

**Comment by sense-amr** [comment]
That information is stored in your C:\Users\yourname\AppData\Roaming\TiXL\userSettings.json

<img width="1832" height="955" alt="Image" src="https://github.com/user-attachments/assets/811fd776-4e7d-4c44-a240-d044a9597200" />

Please show what it says for YOURS there..

**Comment by splitlucidity** [comment]
<img width="315" height="181" alt="Image" src="https://github.com/user-attachments/assets/59929019-6304-4e1c-aa79-045ac59be4f6" />

**Comment by sense-amr** [comment]
lets see if we can force it to create a new username .. / namespace .. 

<img width="3440" height="1428" alt="Image" src="https://github.com/user-attachments/assets/b0e831af-541a-4e36-b808-3b2f283bb577" />
yes we can 

<img width="961" height="548" alt="Image" src="https://github.com/user-attachments/assets/6ec4d0c8-7620-4b64-9889-eed4e5080c48" />

then i just created a NEW project with out even making the namespace .. because it defaulted to using my computer username

**Comment by sense-amr** [comment]
Ah ha there is the problem 

<img width="396" height="96" alt="Image" src="https://github.com/user-attachments/assets/d2651b1d-0bec-4fd9-a72b-97730ed70e75" />

If its using your computer username THAT is not a valid namespace .. it has numbers ..

**Comment by sense-amr** [comment]
are you on the TiXL discord?  i would happily go through this with you

**Comment by splitlucidity** [comment]
I am not on the discord, but I would happily join! Lemme find it and join

**Comment by sense-amr** [comment]
feel free to message me there

**Comment by splitlucidity** [comment]
on DM or through installation and setup?

**Comment by sense-amr** [comment]
DM me and then we can go through it and if it ultimately doesnt work i will furbish you with a most recent version that WILL definitely work

**Comment by splitlucidity** [comment]
Sweet, thank you so much for helping me through with all of this!

**Comment by pixtur** [comment]
@sense-amr that is an _excellent_  find. Normally numbers should be prevented in namespaces!

**Comment by sense-amr** [comment]
@domportera and @pixtur This is a Very perculiar problem .. i wasn't able to FIX the issue for @splitlucidity but i was able to hack a fix by creating a new project on my machine with identical settings for him using his namespace and same location and drive name for TixL Projects .. it worked .. but he is still unable to create a new project himself .. and this is very strange .. i fear also its very difficult to reproduce because i have no issues with making a new project .. and i have given him the last build version of TiXL from the github source.. anyway a work around was found .. and he is able to use TiXL for the first time .. but yeh this is a weird one!

**Comment by domportera** [comment]
perhaps he should try changing his "user" name in tixl - im not sure if there is a UI for this at the moment, but in the tixl config in `%appdata%/TiXL/userSettings.json` there is a   "UserName" field - presumably this is your numeric windows username,
 but you can modify it to be something valid (needs to start with a letter)

as for what we should do about this - on app initialization when no userSettings.json exists (or the username is otherwise an invalid namespace item), we should prompt a username change

**Comment by sense-amr** [comment]
> perhaps he should try changing his "user" name in tixl - im not sure if there is a UI for this at the moment, but in the tixl config in `%appdata%/TiXL/userSettings.json` there is a "UserName" field - presumably this is your numeric windows username, but you can modify it to be something valid (needs to start with a letter)
> 
> as for what we should do about this - on app initialization when no userSettings.json exists (or the username is otherwise an invalid namespace item), we should prompt a username change

we did all that :) .. it didnt change the result ..

https://github.com/tixl3d/tixl/issues/738#issuecomment-3213608524
did all of it :D still no dice 
but i did find a hack work around ..

**Comment by sense-amr** [comment]
Now that i think about it .. regardless of if we are using a custom projects directory TiXL will ALWAYS want to write to user/appdata  etc.. and in THIS case that means (number)/appdata .. IF TiXL has a problem with the username of the computer being a number which in this case it is .. this might suggest a reason why there is an issue with functionality in general that requires writing to user/appdata

**Comment by domportera** [comment]
it's hard to say without new logs after you've helped out - there might be other issues at hand. numbers as a directory name shouldnt be an issue outside of namespace-related things, and it seems like you should have sorted that out for new projects, unless there's some errant logic in tixl that overwrites custom usernames

**Comment by sense-amr** [comment]
> it's hard to say without new logs after you've helped out - there might be other issues at hand. numbers as a directory name shouldnt be an issue outside of namespace-related things, and it seems like you should have sorted that out for new projects, unless there's some errant logic in tixl that overwrites custom usernames

the strange thing was I was about to create a new project on my machine .. with exactly the identical settings and folder references as was in @splitlucidity 's i used splitludicity as a namespace / username and the same drive location and folder name for projects .. and it WORKED .. but he still cannot make a new project himself .. but he can use the hacked one i created

**Comment by domportera** [comment]
> > it's hard to say without new logs after you've helped out - there might be other issues at hand. numbers as a directory name shouldnt be an issue outside of namespace-related things, and it seems like you should have sorted that out for new projects, unless there's some errant logic in tixl that overwrites custom usernames
> 
> the strange thing was I was about to create a new project on my machine .. with exactly the identical settings and folder references as was in @splitlucidity 's i used splitludicity as a namespace / username and the same drive location and folder name for projects .. and it WORKED .. but he still cannot make a new project himself .. but he can use the hacked one i created 

I'd assume he can't compile it then. would be nice to see if he can create a new operator via Duplicating an existing one to his project

**Comment by HorstBaerbel** [comment]
I had the same problem on the first start of a fresh TiXL 4.0.5.3 install. I used "GWP25" as a name and tried with and without a namespace "GWP". Both threw an error. Both folders were created though. After restarting TiXL both projects showed up. I deleted the folders, restarted TiXL again and same name "GWP25" worked 🤷‍♂️.
<img width="1311" height="674" alt="Image" src="https://github.com/user-attachments/assets/efd4c1e6-7a9e-47f9-84d6-57e4a8bd1927" />

**Comment by 0xc1c4da** [comment]
I had a similar error with v4.0.6.1 fd28bebd (installing on wine Linux), I unfortunately cannot determine exactly how I 'fixed' it, the only difference is that I changed my username between installs.

```bash
export WINEPREFIX="$HOME/wine/tixl"
mkdir -p $WINEPREFIX
wine wineboot --init && wineserver -w
./winetricks -q corefonts
./winetricks -q d3dcompiler_43 d3dcompiler_47
./winetricks -q dxvk
wine ~/Downloads/Tixl-v4.0.6.1.exe
```
Installer completes , .net installation completes, application launches, I chose a username `j` the same as my Linux username, and there was no MyProject, and I could not create a new project.

at this stage I `rm -rf $WINEPREFIX` and repeated the steps above, but this time chose `cicada` as my username, and on launch, MyProject exists and I can create new projects with no issue.

**Comment by domportera** [comment]
This is strange. next time anybody runs into this, please gather any log information you can! it'd be nice if the project creation error's copy-to-clipboard actually copied the build logs - i'll see if i can add this.

this issue *might* have something to do with dotnet restore ¯\_(ツ)_/¯

**Comment by Dimensionsmith** [comment]
I'm having similar issues with creating a new project, (windows 10) . 
I've gathered some log info here . 

[TiXL Startup.txt](https://github.com/user-attachments/files/22309890/TiXL.Startup.txt)

![Image](https://github.com/user-attachments/assets/e26cc777-d2c2-4d84-9d75-46f080d96b72)

**Comment by Dimensionsmith** [comment]
Also may be handy to know? I've tried various versions , all with the same problem - i think in the latest version i was able to load up the demo files, but on this version 4.0.5 i'm not able for some reason.

**Comment by domportera** [comment]
it seems like you have an issue with your project's c# file - it was corrupted in some way. you could open `MyProject.csproj` in your IDE (i.e. visual studio, etc) and it should syntax-highlight the issue in `MyProject.cs`. from the looks of it, there are some incomplete brackets or issue with where things are declared

**Comment by Dimensionsmith** [comment]
yes - there are 5 problems and like you say, related to curly brackets.  I'm trying to figure out how to fix it. 
Thanks for pointing this out!

**Comment by domportera** [comment]
if you're having trouble, feel free to send the file here and i can patch it up. do you know how this could have happened?

**Comment by scansion87** [comment]
Hello,

unfortunately im having the same issue, my tixl was running kind of ok, but some projects stopped showing and more and more started to get corrupted / not show so i tried fresh install, removing all trace and now i cannot create or open anything in the app. 

i chose my username to set the directory when first starting the app, which it created the folder in documents, now whenever i try to create a workspace i get this failed dialog, however it is still creating folders in the documents.

if i go into the prefs i can see the directories for projects etc is set correctly.

I can run a couple of backup projects, however if i try to save any capsules i get immediate crashes.

I have switched off all firewalls and checked all write permissions but am kind of stuck.

<img width="729" height="747" alt="Image" src="https://github.com/user-attachments/assets/c1686ee6-a882-44ec-a6d1-5a2979316156" />

**Comment by domportera** [comment]
@scansion87 can you try again and then scroll down on that window? there should be an option to copy debug information specific to this issue, that way you can paste it right in here and we can diagnose properly

**Comment by scansion87** [comment]
<img width="1398" height="883" alt="Image" src="https://github.com/user-attachments/assets/40fe279b-3590-4fc7-a2d4-70ad8332f0e3" />


i also constantly get this error when starting the app in the logs:

Warning: Home symbol 4a2baf40-4eef-436d-af93-ba26b06f0c8d not found

## Failure Log: Restore output: ```
  Determining projects to restore...
  Restored C:\Users\61474\documents\TiXL\loadnew\loadnew.csproj (in 46 ms).

```
 Build output: 
```
  Determining projects to restore...
  Restored C:\Users\61474\documents\TiXL\loadnew\loadnew.csproj (in 46 ms).

```
 
--- 
## Project details
Tixl username:matikone
Project namespace:
Project name:loadnew
Project full name:matikone.loadnew
Projects directory:C:\Users\61474\documents/TiXL
--- 
## Additional details<!--Insert any relevant additional details here, if any-->



this is when i try to create a new symbol:

TiXL crashed. We're really sorry.

The last backup was saved 12 min ago to...
C:\Users\61474\AppData\Roaming\TiXL\Backup
 
Please refer to Help > Using Backups on what to do next.

System.Exception: Could not find instance with id 7c327bfb-9bcc-40f3-9de7-72eb26d42328 and child id e0bbc4cf-b5cf-8ac5-9762-7d6d2e23d0ab. Symbol type: ""
   at T3.Editor.UiModel.ProjectHandling.ProjectView.InstanceView.get_Instance() in C:\Users\pixtur\dev\tooll\tixl\Editor\UiModel\ProjectHandling\ProjectView.InstanceView.cs:line 98
   at T3.Editor.Gui.Graph.Window.GraphWindow.DrawContent() in C:\Users\pixtur\dev\tooll\tixl\Editor\Gui\Graph\Window\GraphWindow.cs:line 235
   at T3.Editor.Gui.Windows.Window.DrawOneInstance() in C:\Users\pixtur\dev\tooll\tixl\Editor\Gui\Windows\Window.cs:line 81
   at T3.Editor.Gui.Windows.Window.DrawAllInstances() in C:\Users\pixtur\dev\tooll\tixl\Editor\Gui\Windows\Window.cs:line 168
   at T3.Editor.Gui.Windows.Layouts.WindowManager.Draw() in C:\Users\pixtur\dev\tooll\tixl\Editor\Gui\Windows\Layouts\WindowManager.cs:line 31
   at T3.Editor.Gui.T3Ui.ProcessFrame() in C:\Users\pixtur\dev\tooll\tixl\Editor\Gui\T3UI.cs:line 113
   at T3.Editor.Gui.WindowsUiContentDrawer.RenderCallback() in C:\Users\pixtur\dev\tooll\tixl\Editor\Gui\WindowsUiContentDrawer.cs:line 160
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Editor.App.AppWindow.RunRenderLoop(Action callback) in C:\Users\pixtur\dev\tooll\tixl\Editor\App\AppWindow.cs:line 115
   at T3.Editor.Program.Main(String[] args) in C:\Users\pixtur\dev\tooll\tixl\Editor\Program.cs:line 201

**Comment by scansion87** [comment]
i also tried renaming the folder in appdata so it creates a new one on startup and prompts me for another username, and tried some other combinations but no change, also tried installing the app on other drives etc with no change, changing save location aswell... could it be a permissions issue with windows 11?  

i also tried creating a whole new user account for windows with an admin role and still get identical results, aswell as clean uninstall and reinstall multiple times with different versions of tixl 4... i can normally figure stuff but after a solid day of trying everything im pretty much stumped...im kind of assuming its more my pc than tixl though.

**Comment by Gleix** [comment]
Fixed this issue on my Win11 machine by adding the dotnet location to the environment variables manually - you can do this by:  

1. Open your environment variables (Under System Properties > Advanced > Environment Variables...)
2. Add "C:\Program Files\dotnet" or wherever your dotnet.exe is located to Path (Select Path for your user or system, click Edit, click new, add the location of the installation.) 

***If your dotnot installed elsewhere, or the above doesn't work, you may need to instead create a new Variable called "DOTNET_ROOT" with the same value (location of your dotnet installation). 

This seems to have fixed the issue for v4.0.6.3 and the current alpha v4.1.0.4. 

My best guess is that most people end up with Microsoft's DotNet SDKs installed via other software installers like TiXL's which make it part of their process which, for whatever reason, never tells it to set these values in the environment variables so depending on the way the software is coded it may not know where to look for dotnet.exe which is required for certain functionality.

Excited to try the software coming from TouchDesigner world :)

**Comment by scansion87** [comment]
fingers crossed but i think i may of fixed my issue, dotnet was referencing an old install of visual studio that no longer existed on an external device.

**Comment by visuality** [comment]
Dont know if you guys figured it out, but I fixed my error pretty easily and quickly.  You have to go the system preference of the app, 1st launch the app, then go to the menu, Tixel/Settings Menu/Projects/Project Directory's/ Erase your current default project directory path ==> Then reset to a new path, (that doesnt happen automagically you have to manually set the path) you have to copy and paste in a path, so go someone on your computer NOT heavily protected heavily by Windows, you desktop is good test, make a folder, "test", do NOT put spaces in the name, just to save yourself from potential headaches :P then copy the address of that folder from the address bar of that folder, paste it into the "directory path" setting you just erased (that is manually setting path), restart the app OR  just tryi to use it asap, works fine, Do the process all over against to set it to your prefered folder if you did not do that instead of following my instructions like a robot. Have a blast, using the beautiful work of and art and technology.
